steps:
  - name: 'gcr.io/cloud-builders/gradle:5.6.2-jdk-8'
    args: ['build', '-x', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/companieshouse', '.']
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/companieshouse"]
  - name: 'aquasec/trivy'
      entrypoint: '/bin/sh'
      args:
        - '-c'
        - |
          trivy eu.gcr.io/$PROJECT_ID/companieshouse:latest
          echo "Starting checking vulnerabilities...."
          TAG="latest"
          trivy "${DOCKER_USER}/${PRODUCT}:${TAG}" > vulnerability-report.txt
          critical_vulnerability=$(grep CRITICAL: vulnerability-report.txt | sed -n -e 's/^.*CRITICAL: //p' | cut -c1-1)
          echo "Vulnerabilities Report Generated..."
          if [ "$critical_vulnerability" != "0" ]; then
            echo "Critical Vulnerabilities Identified, review the attached vulnerability report."
            echo "Fix the CRITICAL vulnerabilities to proceed with the deployment."
            exit 1
          else
            echo "Everything is good."
            echo "No Critical Vulnerabilities Identified, review full list of other vulnerabilities identified."
          fi
          echo "Trivy Vulnerabilities Check Ends.."
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'companieshouse',
      '--image',
      'gcr.io/$PROJECT_ID/companieshouse',
      '--region',
      'europe-west1',
      '--allow-unauthenticated',
      '--platform',
      'managed',
    ]
